eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8700}/eureka/
spring.application.name=gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.routes[0].id=usuarios
spring.cloud.gateway.routes[0].uri=lb://usuarios
spring.cloud.gateway.routes[0].predicates[0]=Path=/usuarios,/usuarios/**
spring.cloud.gateway.routes[1].id=reservas
spring.cloud.gateway.routes[1].uri=lb://reservas
spring.cloud.gateway.routes[1].predicates[0]=Path=/reservas,/reservas/**
spring.cloud.gateway.routes[2].id=comentarios
spring.cloud.gateway.routes[2].uri=lb://comentarios
spring.cloud.gateway.routes[2].predicates[0]=Path=/comentarios,/comentarios/**
server.port=8080
