spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8703
spring.data.mongodb.uri=mongodb://localhost:27017/comentariosProyecto
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.application.name=comentarios
spring.graphql.path=/comentarios

usuarios.service.url=${USUARIOS_SERVICE_URL:http://localhost:8702}
reservas.service.url=${RESERVAS_SERVICE_URL:http://localhost:8701}

eureka.client.serviceUrl.defaultZone=http://localhost:8700/eureka/
springdoc.api-docs.path=/api-comentarios
spring.graphql.graphiql.enabled=true
